services:
  redis:
    image: redis:latest
    container_name: fusion-host-redis
    restart: unless-stopped
    ports:
      - "${REDIS_HOST:-127.0.0.1}:${REDIS_PORT:-6379}:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    networks:
      - fusion-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis-data:
    driver: local

networks:
  fusion-network:
    driver: bridge